services:
  app:
    build:
      context: .
      target: builder
    container_name: subra-local-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: pnpm dev --host
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3 